import{a as f,i as n,S as w}from"./assets/vendor-Do60_h77.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com/api/";const m=async(i,r)=>{try{const{data:o}=await f.get("",{params:{key:"55675620-3b63b7fb21ffc0e94edd19f24",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return o}catch{n.error({message:"No data found"})}},a={searchForm:document.querySelector(".form"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},v=new w(".gallery a",{captionsData:"alt",captionDelay:250}),g=i=>{const r=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:c,comments:L,downloads:b})=>`<li class="gallery-item">
    <a class="gallery-link" href="${s}">
      <img
        class="gallery-image"
        src="${o}"
        alt="${e}"
      />
      <div class="info-wrapper">
      <p class="info">Likes: ${t}</p>
      <p class="info">Views: ${c}</p>
      <p class="info">Comments: ${L}</p>
      <p class="info">Downloads: ${b}</p>
      </div>
    </a>
  </li>`).join("");a.galleryList.insertAdjacentHTML("beforeend",r),v.refresh()};function B(){a.galleryList.innerHTML=""}function p(){a.loader.classList.remove("hidden")}function h(){a.loader.classList.add("hidden")}function y(){a.loadMoreBtn.classList.remove("closed")}function d(){a.loadMoreBtn.classList.add("closed")}let l=1,u="";a.searchForm.addEventListener("submit",M);a.loadMoreBtn.addEventListener("click",S);async function M(i){try{i.preventDefault(),B(),d();const{target:r}=i,o=r.elements["search-text"].value.trim();if(!o){n.warning({message:"Please, enter search query",position:"topRight"});return}u=o,l=1,p();const{hits:s,totalHits:e}=await m(u,l);if(s.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"plum"});return}g(s),l*15<e?y():(d(),n.warning({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",backgroundColor:"plum"})),r.reset()}catch{n.error({message:"Error fetch images",position:"topRight"})}finally{h()}}async function S(i){l++,d(),p();try{const{hits:r,totalHits:o}=await m(u,l);g(r);const s=a.galleryList.children[0].getBoundingClientRect().height;scrollBy({top:s*2,behavior:"smooth"}),l*15>=o?(d(),n.warning({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",backgroundColor:"plum"})):y()}catch{n.error({message:"Error fetch images",position:"topRight"})}finally{h()}}
//# sourceMappingURL=index.js.map
